ps:
	iverilog -o pixelSensor -c pixelSensor.fl
	vvp -n pixelSensor

pa:
	iverilog -g2012 -o pixelArray -c pixelArray.fl
	vvp -n pixelArray

pstate:
	iverilog -g2012 -o pixelState -c pixelState.fl
	vvp -n pixelState

ptop:
	iverilog -g2012 -o pixelTop -c pixelTop.fl
	vvp -n pixelTop

